[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# [THAY ĐỔI QUAN TRỌNG]
# Dòng này nói với Python: "Hãy coi toàn bộ thư mục 'src' là một gói (package) duy nhất có tên là 'bot'"
package-dir = {"bot" = "src"}
# Chúng ta không cần 'find' nữa vì đã chỉ định rõ ràng
packages = ["bot"]

[project]
name = "ryuuko-bot"
version = "1.3.4" # Tôi cập nhật phiên bản cho bạn
authors = [
  { name="Zang Vũ", email="zvwgvx@polydevs.uk" },
]
description = "A Discord bot."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "python-dotenv>=0.21.0",
    "discord.py>=2.3.2",
    "requests>=2.28.0",
    "pymongo>=4.0.0",
    "Pillow>=10.0.0",
    "aiohttp>=3.9.0",
    "urllib3>=1.21.0",
    "tiktoken>=0.4.0",
    "colorama>=0.4.6",
    "google-genai>=0.4.0",
    "fastapi>=0.118.0" # Đã thêm fastapi
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0"
]

# [THAY ĐỔI QUAN TRỌNG]
# Entry point này bây giờ sẽ hoạt động chính xác
[project.scripts]
start = "bot.__main__:main"